### PR TITLE
Change configuration and book for the integration of AsciiDoc

### PR DESCRIPTION
**Pull request by ThibaultAr**
Hello,
I change the Pillar.conf and the book to add the fact that pillar can now export to AsciiDoc.

### CODE REVIEW

**Comment by cdlm** [comment]
Looks good to me. Pillar is not very robust when the configuration specifies an exporter that is not available in the image… but that's a separate issue.

**Comment by ThibaultAr** [comment]
The exporter is in the development image !
And i think the download.sh script load the development version.

**Comment by cdlm** [comment]
I know. Still, should the image *crash* because you did `git pull` but forgot `./download.sh`?

**Comment by ThibaultAr** [comment]
Oh OK i see the point ! So now we added this to the conf Pillar will crash ?

**Comment by cdlm** [comment]
Unless you run dowload.sh, yes

Le jeudi 10 mars 2016, Thibault Arloing <notifications@github.com> a écrit :

> Oh OK i see the point ! So now we added this to the conf Pillar will crash
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SquareBracketAssociates/EnterprisePharo/pull/68#issuecomment-194980514>
> .
>


-- 
Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet

**Comment by DamienCassou** [comment]
do we want to generate the asciidoc by default? We don't have any use for it in EnterprisePharo now.

**Comment by ThibaultAr** [comment]
I update my last commit to remove the default generation of asciidoc.

**Comment by DamienCassou** [comment]
Thanks

**Pull request merged**
