### PR TITLE
Update VoyageAdditionalText.pier

### PR DESCRIPTION
**Pull request by SabineManaa**
This are my suggestions concerning 
http://forum.world.st/Mongo-find-object-by-id-tp4842231p4843330.html

Please feel free to change or delete.
I am interested in your feedback.

### CODE REVIEW

**Comment by DamienCassou** [comment]
Would it make sense to propose the change on the Voyage chapter directly?

**Comment by Ducasse** [comment]
Damien I do not know. I created the file so that Johan can handle it the way he wants.

**Comment by jfabry** [comment]
I will have a look at this later this week.

**Comment by SabineManaa** [comment]
Hi Johan, did you check it?

**Comment by jfabry** [comment]
Sorry for the delay. I will start on it now.

**Comment by jfabry** [comment]
Sabine, I have integrated the bulk of your suggestions. Have a look at https://github.com/SquareBracketAssociates/EnterprisePharo/commit/5ef39b90c459e094e5fadeb9c31e9a8e8888a194 and https://github.com/SquareBracketAssociates/EnterprisePharo/commit/4beab67d22cab4301ef39bc186343ee9b33753b8 If you have any comments please mail me at my jfabry@dcc e-mail address (to not spam the other people) and we can chat about it.

**Comment by SabineManaa** [comment]
Hi Johan, the changes are fine, thanks! Sabine

2015-08-30 19:12 GMT+02:00 Johan Fabry <notifications@github.com>:

**Pull request merged**
