### PR TITLE
Use new sbabook listings

### PR DESCRIPTION
**Pull request by DamienCassou**
Adapt project to [new sbabook listings](https://github.com/cdlm/sbabook/tree/listing-environment).

### CODE REVIEW

**Comment by DamienCassou** [comment]
/cc @cdlm I can't compile the generated LaTeX anymore. I have the impression it is because of this code which is not valid anymore:

```latex
\code{/hi}, \code{/users/name\textgreater{}}
```

**Comment by DamienCassou** [comment]
```
l.97 ... \code{/users/\textless{}name\textgreater{}}

./Teapot/Teapot.tex:97:  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by cdlm** [comment]
Ah yes, I've redefined `\code` to use `\lstinline` from `listings.sty`. So it's nearly like `\verb` now: its argument shouldn't be escaped, and delimited by an arbitrary character: `\code|text|` or `\code§text§`.

You can also use curly braces, but of course only if the argument does not contain any: `\code{text without curlies}`.

**Comment by DamienCassou** [comment]
ok, I implemented that as well. Now, I have to read section 6.1 de texdoc listings

**Comment by DamienCassou** [comment]
I decide we will live with the current situation for the moment. When a user decides to put a monospace format inside a caption, we will decide what to do.

**Comment by cdlm** [comment]
I didn't manage to get it to work. The problem is that the caption is written in a file to be reloaded in the list of figures, and that precludes many macros. Apparently people get it to work using `\protect`, but I suspect it depends on the document class implementation. :rage:

**Comment by DamienCassou** [comment]
@cdlm argh, I think I have a case already

```pillar
----==\{{{\\begin{scriptsize}}}}==--
```

this should be strikethrough and monospace. Currently, Pillar generates the following which doesn't compile:

```latex
\sout{\code§{{{\begin{scriptsize}}}}§}
```

**Comment by DamienCassou** [comment]
To make that work, I have to write the following latex code instead:

```latex
\sout{\code§\{\{\{\\begin\{scriptsize\}\}\}\}§}
```

but (yes, it would be too simple otherwise), if you put backslashes in `\code` outside of `\sout`, backslashes are displayed as is. So, the backslash protection can only be used when `\code` is used in an argument...

**Comment by DamienCassou** [comment]
I've implemented something (based on `thisContext` :-)). Let's wait for a new build to check.

**Comment by cdlm** [comment]
:laughing: 

Other possible solution, revert to the previous export logic, but use a macro `\textcode` (just so that it's not explicitly `\texttt`. I want to keep `\code` as the one we use when writing in LaTeX directly.

**Comment by DamienCassou** [comment]
You propose that Pillar exports to `\textcode` when inside an argument and to `\code` otherwise? How would you define `\textcode` and why can't we use `\textcode` everywhere then? How is this approach better than what I've just implemented?

**Comment by cdlm** [comment]
No, just use `\textcode` everywhere, escaping everything inside. It would be defined by `\let\textcode\texttt` and mean *write this in the code font* (form-level macro) instead of *this is verbatim text* (content-level macro).

**Comment by DamienCassou** [comment]
done

**Pull request merged**
